# Title moved to _data/translations.yml
description: Beautiful property for sale in the Ardèche region of France
baseurl: ""
url: "https://sale.domainedelamiral.com"
markdown: kramdown
languages: ["en", "fr", "de", "it", "nl"]
default_lang: "en"
exclude_from_localizations: ["images", "css", "js", "fonts", "favicon.ico"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "vendor"]
price: 750 000 €
