title:
  en: "Domaine & B&B in the Ardèche for sale"
  fr: "Domaine & Chambres d'hôtes en Ardèche à vendre"
  de: "Domaine & B&B in der Ardèche zu verkaufen"
  it: "Domaine & B&B nell'Ardèche in vendita"
  nl: "Domaine & B&B in de Ardèche te koop"
description: Beautiful property for sale in the Ardèche region of France
baseurl: ""
url: "https://sale.domainedelamiral.com"
markdown: kramdown
languages: ["en", "fr", "de", "it", "nl"]
default_lang: "en"
exclude: ["README.md", "Gemfile", "Gemfile.lock", "vendor"]
price: 875 000 €