name: Build Sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Using Ruby 2.7 which is compatible with the current dependencies
          bundler-cache: true
          
      - name: Install dependencies
        run: bundle install --path vendor/bundle
      
      - name: Build site
        run: bundle exec jekyll build
        
      # Save the generated sitemap and robots.txt as artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site-output
          path: |
            sitemap.xml
            robots.txt